# Generated by Django 5.1.3 on 2025-01-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_activetokens_token_alter_activetokens_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetokens',
            name='token',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
